# python lightning/models/faster_rcnn_pl.py --max_iters 50000 --output_dir outputs/omniact_50k_lr_0.0025_diff_app_desktop --base_lr 0.0025 --dataset_path /home/waynechi/dev/omniact/coco_diff_app_desktop{}.json --img_path /
# python lightning/models/faster_rcnn_pl.py --max_iters 50000 --epochs 20 --devices 4 --output_dir outputs/comcrawl_50k_lr_0.0025 --base_lr 0.0025 --dataset_path /home/waynechi/dev/gui-agent/bounding_boxes/datasets/comcrawl_2_small/coco{}.json --img_path / --freeze_backbone
# python lightning/models/faster_rcnn_pl.py --max_iters 50000 --epochs 20 --devices 4 --output_dir outputs/comcrawl_50k_lr_0.0025_unfrozen --base_lr 0.0025 --dataset_path /home/waynechi/dev/gui-agent/bounding_boxes/datasets/comcrawl_2_small/coco{}.json --img_path /
# python lightning/models/faster_rcnn_pl.py --max_iters 5000 --epochs 1 --devices 4 --batch_size 64 --output_dir outputs/comcrawl_2_large_test_1 --base_lr 0.0025 --dataset_path /home/waynechi/dev/gui-agent/bounding_boxes/datasets/comcrawl_2_large/coco{}.json --img_path / --config_path /home/waynechi/dev/gui-agent/bounding_boxes/cfg/faster_rcnn_large.yaml --optimizer adamw
python lightning/models/faster_rcnn_pl.py --max_iters 5000 --epochs 1 --devices 4 --batch_size 32 --output_dir outputs/comcrawl_2_large_test_2 --base_lr 0.0025 --dataset_path /home/waynechi/dev/gui-agent/bounding_boxes/datasets/comcrawl_2_large/coco{}.json --img_path / --config_path /home/waynechi/dev/gui-agent/bounding_boxes/cfg/faster_rcnn_large.yaml --optimizer adamw
python lightning/models/faster_rcnn_pl.py --max_iters 5000 --epochs 1 --devices 4 --batch_size 16 --output_dir outputs/comcrawl_2_large_test_3 --base_lr 0.0025 --dataset_path /home/waynechi/dev/gui-agent/bounding_boxes/datasets/comcrawl_2_large/coco{}.json --img_path / --config_path /home/waynechi/dev/gui-agent/bounding_boxes/cfg/faster_rcnn_large.yaml --optimizer adamw
python lightning/models/faster_rcnn_pl.py --max_iters 5000 --epochs 1 --devices 4 --batch_size 32 --output_dir outputs/comcrawl_2_large_test_4 --base_lr 0.005 --dataset_path /home/waynechi/dev/gui-agent/bounding_boxes/datasets/comcrawl_2_large/coco{}.json --img_path / --config_path /home/waynechi/dev/gui-agent/bounding_boxes/cfg/faster_rcnn_large.yaml --optimizer adamw
python lightning/models/faster_rcnn_pl.py --max_iters 5000 --epochs 1 --devices 4 --batch_size 32 --output_dir outputs/comcrawl_2_large_test_5 --base_lr 0.001 --dataset_path /home/waynechi/dev/gui-agent/bounding_boxes/datasets/comcrawl_2_large/coco{}.json --img_path / --config_path /home/waynechi/dev/gui-agent/bounding_boxes/cfg/faster_rcnn_large.yaml --optimizer adamw
python lightning/models/faster_rcnn_pl.py --max_iters 5000 --epochs 1 --devices 4 --batch_size 32 --output_dir outputs/comcrawl_2_large_test_6 --base_lr 0.00075 --dataset_path /home/waynechi/dev/gui-agent/bounding_boxes/datasets/comcrawl_2_large/coco{}.json --img_path / --config_path /home/waynechi/dev/gui-agent/bounding_boxes/cfg/faster_rcnn_large.yaml --optimizer adamw
